version: '3.0'

services:
  nodejs-service:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - ${PORT_SERVICE}:${PORT_SERVICE}
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRE_DATABASE}
      POSTGRES_USER: ${POSTGRE_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRE_PASSWORD}
      DATABASE_URL: postgresql://${POSTGRE_USERNAME}:${POSTGRE_PASSWORD}@database:5432/${POSTGRE_DATABASE}?schema=public
    depends_on:
      - database
    networks:
      - user-defined

  database:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRE_DATABASE}
      POSTGRES_USER: ${POSTGRE_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRE_PASSWORD}
    ports:
      - ${PORT_DB}:${PORT_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - user-defined

volumes:
  db-data: ~

networks:
  user-defined:
    driver: bridge
